"""Create all database tables

Revision ID: 34e675c78fa7
Revises: 
Create Date: 2020-06-18 12:10:22.216825

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
# from app.models import db, User, Song, Comment, Favorite


# revision identifiers, used by Alembic.
revision = '34e675c78fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
                                  sa.Column('id', sa.Integer(),
                                            nullable=False),
                                  sa.Column('email', sa.String(
                                            length=50), nullable=False),
                                  sa.Column('nickname', sa.String(
                                            length=50), nullable=False),
                                  sa.PrimaryKeyConstraint('id'),
                                  sa.UniqueConstraint('email')
                                  )
    songs_table = op.create_table('songs',
                                  sa.Column('id', sa.Integer(),
                                            nullable=False),
                                  sa.Column(
                                      'title', sa.String(), nullable=False),
                                  sa.Column(
                                      'genre', sa.String(), nullable=False),
                                  sa.Column('description',
                                            sa.Text(), nullable=True),
                                  sa.Column(
                                      'image_url', sa.String(), nullable=True),
                                  sa.Column(
                                      'song_url', sa.String(), nullable=False),
                                  sa.Column(
                                      'user_id', sa.Integer(), nullable=False),
                                  sa.Column(
                                      'created_at', sa.DateTime(), nullable=True),
                                  sa.ForeignKeyConstraint(
                                      ['user_id'], ['users.id'], ),
                                  sa.PrimaryKeyConstraint('id')
                                  )
    comments_table = op.create_table('comments',
                                     sa.Column(
                                         'id', sa.Integer(), nullable=False),
                                     sa.Column(
                                         'comment', sa.Text(), nullable=False),
                                     sa.Column(
                                         'user_id', sa.Integer(), nullable=False),
                                     sa.Column(
                                         'song_id', sa.Integer(), nullable=False),
                                     sa.ForeignKeyConstraint(
                                         ['song_id'], ['songs.id'], ),
                                     sa.ForeignKeyConstraint(
                                         ['user_id'], ['users.id'], ),
                                     sa.PrimaryKeyConstraint('id')
                                     )
    favorites_table = op.create_table('favorites',
                                      sa.Column(
                                          'user_id', sa.Integer(), nullable=False),
                                      sa.Column(
                                          'song_id', sa.Integer(), nullable=False),
                                      sa.ForeignKeyConstraint(
                                          ['song_id'], ['songs.id'], ),
                                      sa.ForeignKeyConstraint(
                                          ['user_id'], ['users.id'], )
                                      )

    # Add seeder for users table
    op.bulk_insert(users_table, [
        {
            'nickname': 'AudioSphere App',
            'email': 'audiosphere@audiosphere.com'
        },
        {
            'nickname': 'Jane Doe',
            'email': 'jane.doe@jane.com'
        },
        {
            'nickname': 'Lisa Kang',
            'email': 'lisa@lisa.com'
        }
    ])

    # Add seeder for songs table
    op.bulk_insert(songs_table, [
        {
            'title': 'Gallery',
            'genre': 'R&B',
            'description': 'By Mario Vazquez',
            'image_url': 'https://img.discogs.com/9cZNT2P1Y8J1OEfLQsTyoZZA1jM=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-1286904-1476661289-4461.jpeg.jpg',
            'song_url': 'placeholder',
            'user_id': 1,
            'created_at': datetime.now()
        },
        {
            'title': 'Sorry-Justin Bieber',
            'genre': 'Pop',
            'description': '',
            'image_url': 'https://stereoheadism.files.wordpress.com/2015/10/bieber-purpose.jpg?w=736',
            'song_url': 'placeholder',
            'user_id': 1,
            'created_at': datetime.now()
        },
        {
            'title': 'Killer Whales',
            'genre': 'Indie Rock',
            'description': 'Sung by Smallpools on their album Lovetap!',
            'image_url': 'https://atwoodmagazine.com/wp-content/uploads/2015/04/lovetap_art_FINAL-HIGH-QUALITY.jpg',
            'song_url': 'placeholder',
            'user_id': 2,
            'created_at': datetime.now()
        },
        {
            'title': 'Airplanes',
            'genre': 'Pop',
            'description': 'Throwback song.',
            'image_url': 'https://i.pinimg.com/originals/fa/57/74/fa577490d17d19e635ce5a1499c99898.jpg',
            'song_url': 'placeholder',
            'user_id': 1,
            'created_at': datetime.now()
        },
        {
            'title': 'Portugal',
            'genre': 'Alternative',
            'description': 'My favorite song by Walk the Moon.',
            'image_url': 'https://img.discogs.com/kkyT3ud0I-I5qqCpspDz32Kmc_w=/fit-in/426x423/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6382139-1417872467-2053.jpeg.jpg',
            'song_url': 'placeholder',
            'user_id': 2,
            'created_at': datetime.now()
        },
        {
            'title': 'Because of You',
            'genre': 'Pop',
            'description': 'One of my all time favorite songs.',
            'image_url': 'https://sterling-sound.com/wp-content/uploads/because-of-you.jpg',
            'song_url': 'placeholder',
            'user_id': 1,
            'created_at': datetime.now()
        },
        {
            'title': 'Riptide',
            'genre': 'EDM',
            'description': 'Intense head nods.',
            'image_url': 'https://i1.sndcdn.com/artworks-000574913561-ywoi28-t500x500.jpg',
            'song_url': 'placeholder',
            'user_id': 3,
            'created_at': datetime.now()
        },
        {
            'title': 'Freesol',
            'genre': 'EDM',
            'description': 'By Seven Lions.',
            'image_url': 'https://www.edmsauce.com/wp-content/uploads/2017/04/artworks-000217166678-f89esb-t500x500.jpg',
            'song_url': 'placeholder',
            'user_id': 3,
            'created_at': datetime.now()
        },
        {
            'title': 'Fractures',
            'genre': 'EDM',
            'description': 'Mad feels',
            'image_url': 'https://i2.wp.com/images.genius.com/563802e4fc81ea0a457100c699282cc3.1000x1000x1.jpg?resize=462%2C462&ssl=1',
            'song_url': 'placeholder',
            'user_id': 3,
            'created_at': datetime.now()
        },
        {
            'title': 'Atoms',
            'genre': 'EDM',
            'description': 'Said the Sky Remix',
            'image_url': 'https://i1.sndcdn.com/artworks-000450914991-h78r8l-t500x500.jpg',
            'song_url': 'placeholder',
            'user_id': 3,
            'created_at': datetime.now()
        }
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('songs')
    op.drop_table('users')
    # ### end Alembic commands ###
